HD_Veriler/HD_Veriler/Controllers/ProjeController.cs
using HD_Veriler.Models;
using HD_Veriler.Repositories.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace HD_Veriler.Controllers
{
    public class ProjeController : Controller
    {
        #region tanımlamalar 
        private readonly IDependencyService _dependencyService;
        public ProjeController(IDependencyService dependencyService)
        {
            _dependencyService = dependencyService;

        }

        public IActionResult Index()
        {
            return View();
        }
        #endregion


        #region Proje kategori işlemleri


        [HttpGet]
        public async Task<IActionResult> ProjectCategoryIndex()
        {
            var projectCategories = await _dependencyService.GetProjectCategoryRepository().GetAllAsync();
            return View(projectCategories);
        }

        [HttpGet]
        public IActionResult ProjectCategoryCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ProjectCategoryCreate(ProjectCategory model)
        {
            if (ModelState.IsValid)
            {
                var projectCategoryDTO = _dependencyService.GetMapper().Map<ProjectCategory>(model);
                await _dependencyService.GetProjectCategoryRepository().AddAsync(projectCategoryDTO);
                TempData["Message"] = "Kategori Eklendi";
                return RedirectToAction(nameof(ProjectCategoryIndex));
            }
            TempData["Message"] = "Kategori Eklenemedi";
            return View( model);
        }

        [HttpGet]
        public async Task<IActionResult> ProjectCategoryEdit(int id)
        {
            var projectCategories = await _dependencyService.GetProjectCategoryRepository().GetByIdAsync(id);
            if (projectCategories == null)
            {
                return NotFound();
            }
            return View( projectCategories);
        }

        [HttpPost]
        public async Task<IActionResult> ProjectCategoryEdit(ProjectCategory model)
        {
            if (ModelState.IsValid)
            {
                await _dependencyService.GetProjectCategoryRepository().UpdateAsync(model);
                TempData["Message"] = "Kategori Güncellendi";
                return RedirectToAction(nameof(ProjectCategoryIndex));
            }
            TempData["Message"] = "Kategori Güncellenemedi";
            return View( model);
        }


        [HttpGet]
        public async Task<IActionResult> ProjectCategoryDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var projectCategories = await _dependencyService.GetProjectCategoryRepository().GetByIdAsync(id.Value);
            if (projectCategories == null)
            {
                return NotFound();
            }
            return View( projectCategories);
        }

        [HttpPost, ActionName("ProjectCategoryDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProjectCategoryDelete(int id)
        {
            var projectCategories = await _dependencyService.GetProjectCategoryRepository().GetByIdAsync(id);
            if (projectCategories == null)
            {
                TempData["Message"] = "Kategori Silinemedi";
                return NotFound();
            }
            if (projectCategories?.Active != null)
            {
                projectCategories.Active = false;
                await _dependencyService.GetProjectCategoryRepository().UpdateAsync(projectCategories);
            }
            TempData["Message"] = "Kategori Silindi";
            return RedirectToAction(nameof(ProjectCategoryIndex));
        }

        public async Task<IActionResult> ProjectCategoryDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var projectCategories = await _dependencyService.GetProjectCategoryRepository().GetByIdAsync(id.Value);
            if (projectCategories == null)
            {
                return NotFound();
            }
            return View( projectCategories);
        }



        #endregion

    }
}

HD_Veriler/HD_Veriler/Views/Proje/ProjectCategoryCreate.cshtml
@model ProjectCategory
@{
    ViewData["Title"] = "ProjectCategoryCreate";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<!-- start: page -->
<form class="ecommerce-form action-buttons-fixed" role="form" asp-action="ProjectCategoryCreate" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="row justify-content-center">
        <div class="col-lg-8">
            <section class="card card-modern card-big-info">
                <div class="card-body">

                    <div class="text-center mb-4">
                        <h2 class="card-big-info-title">Kategori Bilgileri</h2>
                        <p class="card-big-info-desc">Kategori bilgilerini tüm ayrıntılar ve gerekli bilgilerle birlikte buraya ekleyin.</p>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">

                            <div class="form-group">
                                <label class="control-label">Kategori Adı</label>
                                <input type="text" asp-for="ProjeCategoryName" class="form-control form-control-modern" />
                                <span asp-validation-for="ProjeCategoryName"></span>
                            </div>

                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="control-label">Aktif mi?</label>
                                <div class="form-check">
                                    <input type="checkbox" asp-for="Active" class="form-check-input" />
                                    <label class="form-check-label">Evet</label>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </section>
        </div>
    </div>


    <div class="row justify-content-center mt-4">
        <div class="col-lg-6 text-center">
            <button type="submit" value="KAYDET" class="btn btn-primary btn-lg btn-block">
                <i class="bx bx-save"></i> Departmanı Kaydet
            </button>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-lg-6 text-center">
            <a asp-action="ProjectCategoryIndex" class="btn btn-light btn-lg btn-block">
                Geri
            </a>
        </div>
    </div>
</form>
<!-- end: page -->

HD_Veriler/HD_Veriler/Views/Proje/ProjectCategoryDelete.cshtml
@model ProjectCategory
@using HD_Veriler.Helpers;
@using Microsoft.EntityFrameworkCore;
@{
    ViewData["Title"] = "ProjectCategoryDelete";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
    var context = DbContextHelper.CreateContext();
}

<!-- start: page -->
<section class="card">
    <header class="card-header">
        <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
        </div>
        <h2 class="card-title">Proje Kategori Bilgileri</h2>
    </header>
    <div class="card-body">
        <table class="table table-bordered table-striped mb-0" id="datatable-editable" style="font-size: 15px;">
            <thead>
                <tr>
                    <th>Kategori Adı</th>
                    <th>Aktif mi?</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(model => model.ProjeCategoryName)</td>
                    <td>@Html.DisplayFor(model => model.Active)</td>
                </tr>
            </tbody>
        </table>
        <form asp-action="DepartmanDelete" method="post">
            <input type="hidden" asp-for="ProjeCategoryID" />
            <div class="row mt-3">
                <div class="col-12">
                    <div class="text-center">
                        <input type="submit" value="Proje Kategorisini Sil" onclick="return confirm('Silmek istediğinden emin misin?')" class="btn btn-danger">
                        <a asp-action="ProjectCategoryIndex" class="btn btn-secondary ml-2">Geri</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

HD_Veriler/HD_Veriler/Views/Proje/ProjectCategoryDetails.cshtml
@model ProjectCategory
@using HD_Veriler.Helpers
@using Microsoft.EntityFrameworkCore;
@{
    ViewData["Title"] = "ProjectCategoryDetails";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
    var context = DbContextHelper.CreateContext();
}

<div class="row justify-content-center">
    <div class="col-lg-8">
        <section class="card">
            <header class="card-header text-center">
                <h2 class="card-title">@ViewBag.username</h2>
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>
            </header>
            <div class="card-body">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td><strong>Proje Kategori Adı:</strong></td>
                            <td>@Html.DisplayFor(model => model.ProjeCategoryName)</td>
                        </tr>
                        <tr>
                            <td><strong>Aktif mi?</strong></td>
                            <td>@Html.DisplayFor(model => model.Active)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
        <div class="mt-3 text-center">
            <a asp-action="ProjectCategoryIndex" class="btn btn-success btn-lg px-5">
                <i class="bx bx-arrow-back"></i> Proje Kategorilerine Geri Dön
            </a>
        </div>
    </div>
</div>

HD_Veriler/HD_Veriler/Views/Proje/ProjectCategoryEdit.cshtml
@model ProjectCategory
@{
    ViewData["Title"] = "ProjectCategoryEdit";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<!-- start: page -->
<form class="ecommerce-form action-buttons-fixed" role="form" asp-action="/Proje/ProjectCategoryEdit" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="row justify-content-center">
        <div class="col-lg-8">
            <section class="card card-modern card-big-info">
                <div class="card-body">

                    <div class="text-center mb-4">
                        <h2 class="card-big-info-title">Departman Bilgileri</h2>
                        <p class="card-big-info-desc">Departman bilgilerini tüm ayrıntılar ve gerekli bilgilerle birlikte buraya ekleyin.</p>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="control-label">Proje Kategori Adı</label>
                                <input type="text" asp-for="ProjeCategoryName" class="form-control form-control-modern" />
                                <span asp-validation-for="ProjeCategoryName"></span>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="control-label">Kategori aktif mi?</label>
                                <div class="form-check">
                                    <input type="checkbox" asp-for="Active" class="form-check-input" />
                                    <label class="form-check-label">Aktif</label>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </div>
    </div>

    <input type="hidden" asp-for="ProjeCategoryID" />

    <div class="row justify-content-center mt-4">
        <div class="col-lg-8 text-center">
            <button type="submit" value="KAYDET" class="btn btn-success btn-lg" asp-action="ProjectCategoryEdit">
                <i class="bx bx-save"></i> Kategoriyi Güncelle
            </button>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-lg-8 text-center">
            <a asp-action="ProjectCategoryIndex" class="btn btn-light btn-lg">
                Geri
            </a>
        </div>
    </div>
</form>
<!-- end: page -->

HD_Veriler/HD_Veriler/Views/Proje/ProjectCategoryIndex.cshtml
@model IEnumerable<ProjectCategory>
@using HD_Veriler.Helpers
@using Microsoft.EntityFrameworkCore
@{
    ViewData["Title"] = "ProjectCategoryIndex";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
    var context = DbContextHelper.CreateContext();
}

<section class="card">
    <header class="card-header">
        <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle><i class="fas fa-chevron-up"></i></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss><i class="fas fa-times"></i></a>
        </div>
        <h2 class="card-title">Departman Bilgileri</h2>
    </header>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-md-6">
                <a asp-action="ProjectCategoryCreate" asp-controller="Proje" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Yeni Proje Kategorisi Ekle
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover mb-0">
                <thead>
                    <tr>
                        <th>Proje Kategori Adı</th>
                        <th>Aktif mi?</th>
                        <th style="text-align: right;">Düzenle</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string? departmanName = item.Active ? item.ProjeCategoryName : "Olmayan Proje Kategorisi";
                        string background = item.Active ? "" : "bg-danger";
                        <tr class="@background">
                            <td>@departmanName</td>
                            <td>@(item.Active ? "Evet" : "Hayır")</td>
                            <td style="text-align: right;">
                                <div class="btn-group" role="group">
                                    <a class="btn btn-info" asp-action="ProjectCategoryDetails" asp-route-id="@item.ProjeCategoryID" title="Detayları Görüntüle">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="btn btn-warning" asp-action="ProjectCategoryEdit" asp-route-id="@item.ProjeCategoryID" title="Düzenle">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="btn btn-danger" asp-action="ProjectCategoryDelete" asp-route-id="@item.ProjeCategoryID" title="Sil">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>